from tkinter import *
def sign():
    m =Tk()
    m.geometry("600x300")
    name = Label(m,text='Name').pack()
    name = Entry(m)
    name.pack()
    email = Label(m,text='Email Id').pack()
    email = Entry(m)
    email.pack()
    contact = Label(m,text='contact').pack()
    contact = Entry(m)
    contact.pack()
    user = Label(m,text='Username').pack()
    user = Entry(m)
    user.pack()
    password = Label(m,text='password').pack()
    password = Entry(m)
    password.pack()
    button = Button(m,text='SignUp',bg='black',fg='white').pack()
    button = Button(m,text='Exit',command=m.destroy,bg='green',fg='white').pack()
    m.mainloop()
def quiz():
    m = Tk()
    m.geometry("200x150")
    Label(m,text="GBSoftronics",bg='red',fg='white').pack()
    m.mainloop()
    
def signin():
    m =Tk()
    m.geometry("300x150")
    Label(m,text='Welcome in Sign in page').pack()
    user = Label(m,text='Username').pack()
    user = Entry(m)
    user.pack()
    password = Label(m,text='password').pack()
    password = Entry(m)
    password.pack()
    button = Button(m,text='Sign In',command=quiz,bg='black',fg='white').pack()
    button = Button(m,text='Exit',command=m.destroy,bg='silver',fg='black').pack()
    m.mainloop()
    
root = Tk()
Label(root,text = '''Quiz''',height=3,width=20).pack()
button = Button(root,text='SignUp',command=sign  ,bg='black',fg='white').pack()
button1 = Button(root,text='Login',command=signin,width=5,bg='red',fg='white').pack()
root.mainloop()

