def signup():
    root.destroy()
    
    root1 = Tk()
    root1.geometry('700x600')
    root1.config(bg='white')
    root1.resizable(0,0)
    signup_label = Label(root1,text="SignUP ",fg="gold",bg='white',font=("times new romen",50))
    signup_label.pack(pady=20)
    #Information for signup
    name = Label(root1,text="Name",bg='white',font=('Times new romen',15))
    name.pack()
    name_e = Entry(root1)
    name_e.pack()
    email = Label(root1,text="E-mail",bg='white',font=('Times new romen',15))
    email.pack()
    email_e = Entry(root1)
    email_e.pack()
    contact = Label(root1,text="Contact",bg='white',font=('Times new romen',15))
    contact.pack()
    contact_e = Entry(root1)
    contact_e.pack()
    username1 = Label(root1,text="Username",bg='white',font=('Times new romen',15))
    username1.pack()
    username1_e = Entry(root1)
    username1_e.pack()
    password1 = Label(root1,text="Password",bg='white',font=('Times new romen',15))
    password1.pack()
    password1_e = Entry(root1)
    password1_e.pack()

    #Submit
    submit = Button(root1,text='Submit',bg='green',fg='black',width=15,height=2)
    submit.pack(pady=20)
